version: "3.9"

name: ${APP_CONTAINER_NAME}-dev
services:
  quiz-mysql:
    image: mysql:8.0
    container_name: ${APP_NAME}-SQL
    restart: unless-stopped
    networks:
      - quiz_network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_PORT=${MYSQL_PORT}
      - APP_NAME=${APP_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - ${MYSQL_PORT}

networks:
  quiz_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
