version: "3.8"

name: MySQL_8
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: nintyz@ROOT1 # Root password
      MYSQL_DATABASE: d2d # Default database
      MYSQL_USER: day2day # Non-root user
      MYSQL_PASSWORD: nintyz@MYSQL1 # Non-root user password
    volumes:
      - mysql_data:/var/lib/mysql # Mounting persistent volume for data storage
    ports:
      - "3959:3306" # Expose port 3306 for MySQL

volumes:
  mysql_data:
    driver: local # Use local storage for persistent data
